[package]
org="ballerina"
name="yaml"
version="1.0.0"
authors=["Ballerina"]
keywords=["yaml", "parser"]
repository="https://github.com/ballerina-platform/module-ballerina-yaml"
icon = "icon.png"
license=["Apache-2.0"]
distribution = "2201.2.0"
