[package]
org = "ballerina"
name = "yaml"
version = "1.3.2"
authors = ["Ballerina"]
keywords = ["pseudo-yaml"]
repository = "https://github.com/ballerina-platform/module-ballerina-yaml"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"
